#!/bin/sh

DAEMON="positron"
PIDFILE="/var/run/$DAEMON.pid"

# To turn on positron logging
#DAEMON_ARGS="-s"

DAEMON_ARGS=""

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

load_videosys() {
	printf 'Starting %s: ' "$DAEMON"
	# allow the clock to settle
	sleep 1
	# try to help the overlayfs wake up and not throw an EINVAL in directory fsync on store initialization
	[ -f /PositronStore/.HomeKitStore/90.00 ] || touch /PositronStore/.HomeKitStore/.touched
	sync
	sync
	sync
	[ ! -f /PositronStore/.HomeKitStore/.touched ] || rm /PositronStore/.HomeKitStore/.touched
	sync
	sync
	sync

	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" \
		-- $DAEMON_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

# The daemon does not create a pidfile, and use "-m" to instruct start-stop-daemon to create one.
start() {
	logger -s -p daemon.info -t ingenic "Loading of the video system has started"
	export TZ=$(cat /etc/TZ)
	load_ingenic
	#
	#
	# export SENSOR=$(fw_printenv -n sensor)
	export SENSOR=$(cat /proc/jz/sinfo/info | sed -e 's/.*://')
	SENSOR=$(cat /proc/jz/sinfo/info | sed -e 's/.*://')
	if [ "sensor not found" = "$SENSOR" ]; then
		unset SENSOR
	else
		export SENSOR=$SENSOR
	fi
	sleep 1
	load_videosys
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	reload
}

reload() {
	load_videosys
}

case "$1" in
	start|stop|restart|reload)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
