#!/bin/sh

case "$1" in
  start)
    printf "Looking for upgrade.sh on mmc card:\n"
    if [[ `cat /sys/class/mmc_host/mmc0/device/present` = "Y" ]]; then
	    printf "Found device present, waiting for mount\n"
	    sleep 10
      if [[ -f /mnt/mmcblk0p1/upgrade.sh ]]; then
          echo "upgrade.sh found"
         /mnt/mmcblk0p1/upgrade.sh 2>&1 | tee /mnt/mmcblk0p1/upgrade.out
      else
          echo "Not found."
      fi
    fi
    ;;
esac
